/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RandomizerLazyImport = createFileRoute('/randomizer')()
const ParticipantsLazyImport = createFileRoute('/participants')()
const JuryLazyImport = createFileRoute('/jury')()
const BigScreenLazyImport = createFileRoute('/big-screen')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RandomizerLazyRoute = RandomizerLazyImport.update({
  id: '/randomizer',
  path: '/randomizer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/randomizer.lazy').then((d) => d.Route))

const ParticipantsLazyRoute = ParticipantsLazyImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/participants.lazy').then((d) => d.Route))

const JuryLazyRoute = JuryLazyImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jury.lazy').then((d) => d.Route))

const BigScreenLazyRoute = BigScreenLazyImport.update({
  id: '/big-screen',
  path: '/big-screen',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/big-screen.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/big-screen': {
      id: '/big-screen'
      path: '/big-screen'
      fullPath: '/big-screen'
      preLoaderRoute: typeof BigScreenLazyImport
      parentRoute: typeof rootRoute
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryLazyImport
      parentRoute: typeof rootRoute
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsLazyImport
      parentRoute: typeof rootRoute
    }
    '/randomizer': {
      id: '/randomizer'
      path: '/randomizer'
      fullPath: '/randomizer'
      preLoaderRoute: typeof RandomizerLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/big-screen' | '/jury' | '/participants' | '/randomizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/big-screen' | '/jury' | '/participants' | '/randomizer'
  id:
    | '__root__'
    | '/'
    | '/big-screen'
    | '/jury'
    | '/participants'
    | '/randomizer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BigScreenLazyRoute: typeof BigScreenLazyRoute
  JuryLazyRoute: typeof JuryLazyRoute
  ParticipantsLazyRoute: typeof ParticipantsLazyRoute
  RandomizerLazyRoute: typeof RandomizerLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BigScreenLazyRoute: BigScreenLazyRoute,
  JuryLazyRoute: JuryLazyRoute,
  ParticipantsLazyRoute: ParticipantsLazyRoute,
  RandomizerLazyRoute: RandomizerLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/big-screen",
        "/jury",
        "/participants",
        "/randomizer"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/big-screen": {
      "filePath": "big-screen.lazy.tsx"
    },
    "/jury": {
      "filePath": "jury.lazy.tsx"
    },
    "/participants": {
      "filePath": "participants.lazy.tsx"
    },
    "/randomizer": {
      "filePath": "randomizer.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
