/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RandomizerAudienceLazyImport = createFileRoute('/randomizer-audience')()
const RandomizerLazyImport = createFileRoute('/randomizer')()
const QuranPageLazyImport = createFileRoute('/quran-page')()
const ParticipantsLazyImport = createFileRoute('/participants')()
const LoginLazyImport = createFileRoute('/login')()
const JuryLazyImport = createFileRoute('/jury')()
const BigScreenLazyImport = createFileRoute('/big-screen')()
const AdminLazyImport = createFileRoute('/admin')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RandomizerAudienceLazyRoute = RandomizerAudienceLazyImport.update({
  id: '/randomizer-audience',
  path: '/randomizer-audience',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/randomizer-audience.lazy').then((d) => d.Route),
)

const RandomizerLazyRoute = RandomizerLazyImport.update({
  id: '/randomizer',
  path: '/randomizer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/randomizer.lazy').then((d) => d.Route))

const QuranPageLazyRoute = QuranPageLazyImport.update({
  id: '/quran-page',
  path: '/quran-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/quran-page.lazy').then((d) => d.Route))

const ParticipantsLazyRoute = ParticipantsLazyImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/participants.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const JuryLazyRoute = JuryLazyImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/jury.lazy').then((d) => d.Route))

const BigScreenLazyRoute = BigScreenLazyImport.update({
  id: '/big-screen',
  path: '/big-screen',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/big-screen.lazy').then((d) => d.Route))

const AdminLazyRoute = AdminLazyImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/big-screen': {
      id: '/big-screen'
      path: '/big-screen'
      fullPath: '/big-screen'
      preLoaderRoute: typeof BigScreenLazyImport
      parentRoute: typeof rootRoute
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsLazyImport
      parentRoute: typeof rootRoute
    }
    '/quran-page': {
      id: '/quran-page'
      path: '/quran-page'
      fullPath: '/quran-page'
      preLoaderRoute: typeof QuranPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/randomizer': {
      id: '/randomizer'
      path: '/randomizer'
      fullPath: '/randomizer'
      preLoaderRoute: typeof RandomizerLazyImport
      parentRoute: typeof rootRoute
    }
    '/randomizer-audience': {
      id: '/randomizer-audience'
      path: '/randomizer-audience'
      fullPath: '/randomizer-audience'
      preLoaderRoute: typeof RandomizerAudienceLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/login': typeof LoginLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/quran-page': typeof QuranPageLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
  '/randomizer-audience': typeof RandomizerAudienceLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/login': typeof LoginLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/quran-page': typeof QuranPageLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
  '/randomizer-audience': typeof RandomizerAudienceLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRoute
  '/big-screen': typeof BigScreenLazyRoute
  '/jury': typeof JuryLazyRoute
  '/login': typeof LoginLazyRoute
  '/participants': typeof ParticipantsLazyRoute
  '/quran-page': typeof QuranPageLazyRoute
  '/randomizer': typeof RandomizerLazyRoute
  '/randomizer-audience': typeof RandomizerAudienceLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/big-screen'
    | '/jury'
    | '/login'
    | '/participants'
    | '/quran-page'
    | '/randomizer'
    | '/randomizer-audience'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/big-screen'
    | '/jury'
    | '/login'
    | '/participants'
    | '/quran-page'
    | '/randomizer'
    | '/randomizer-audience'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/big-screen'
    | '/jury'
    | '/login'
    | '/participants'
    | '/quran-page'
    | '/randomizer'
    | '/randomizer-audience'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRoute
  BigScreenLazyRoute: typeof BigScreenLazyRoute
  JuryLazyRoute: typeof JuryLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ParticipantsLazyRoute: typeof ParticipantsLazyRoute
  QuranPageLazyRoute: typeof QuranPageLazyRoute
  RandomizerLazyRoute: typeof RandomizerLazyRoute
  RandomizerAudienceLazyRoute: typeof RandomizerAudienceLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRoute,
  BigScreenLazyRoute: BigScreenLazyRoute,
  JuryLazyRoute: JuryLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ParticipantsLazyRoute: ParticipantsLazyRoute,
  QuranPageLazyRoute: QuranPageLazyRoute,
  RandomizerLazyRoute: RandomizerLazyRoute,
  RandomizerAudienceLazyRoute: RandomizerAudienceLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/big-screen",
        "/jury",
        "/login",
        "/participants",
        "/quran-page",
        "/randomizer",
        "/randomizer-audience"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin": {
      "filePath": "admin.lazy.tsx"
    },
    "/big-screen": {
      "filePath": "big-screen.lazy.tsx"
    },
    "/jury": {
      "filePath": "jury.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/participants": {
      "filePath": "participants.lazy.tsx"
    },
    "/quran-page": {
      "filePath": "quran-page.lazy.tsx"
    },
    "/randomizer": {
      "filePath": "randomizer.lazy.tsx"
    },
    "/randomizer-audience": {
      "filePath": "randomizer-audience.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
